Add link to flag in notification message
TheOdinProject/theodinproject pull request #1318
Opened 2020-09-06 16:45 UTC by dvik1950

2020-09-08 22:02 UTC, KevinMulhern requested changes
Looks really good @dvik1950, just a few suggestions :)

2020-09-08 22:02 UTC, KevinMulhern commented on spec/services/notifications/flag_submission_spec.rb
> +    described_class.new(flag)
can this subject all go on one line now?

2020-09-11 20:55 UTC, dvik1950 commented on app/controllers/project_submissions/flags_controller.rb
> +      Notifications::FlagSubmission.new(@flag)
Thanks for the detailed review and sorry for the delay. I made some changes, I'm not sure if I'm on the right track with the changes made regarding this comment though. The comment makes perfect sense but I'm not sure this is the correct way to achieve what you mean 😬

2020-09-12 00:47 UTC, KevinMulhern commented on app/controllers/project_submissions/flags_controller.rb
> +      Notifications::FlagSubmission.new(@flag)
What you've done is exactly what I meant @dvik1950 😄

2020-09-12 00:48 UTC, KevinMulhern commented
This is great, thanks @dvik1950 🚀

2020-09-12 00:48 UTC, KevinMulhern approved these changes

2020-09-12 00:48 UTC, merged

2020-09-12 09:21 UTC, dvik1950 commented on app/controllers/project_submissions/flags_controller.rb
> +      Notifications::FlagSubmission.new(@flag)
glad to hear that 😬