Update form.scss
TheOdinProject/theodinproject pull request #1450
Opened 2020-10-27 19:24 UTC by DoviMaj

.form__section--right-aligned class is obsolete in create form and in edit form @KevinMulhern with those changes.

2020-10-28 01:24 UTC, KevinMulhern commented
The create form has changed at max width, the make solution public label and checkbox should be on the same row as the submit button like it is in production:
![Screenshot 2020-10-28 at 01 23 18](https://user-images.githubusercontent.com/7963776/97379277-5b52bf80-18bc-11eb-8527-b1a3e4b3b79c.png)

2020-10-28 01:28 UTC, KevinMulhern commented
The edit form shouldn't have the make solution public label and checkbox on the row above at max width:

![Screenshot 2020-10-28 at 01 27 01](https://user-images.githubusercontent.com/7963776/97379481-cf8d6300-18bc-11eb-8af3-52da217f5a74.png)

2020-10-28 01:29 UTC, KevinMulhern requested changes

2020-10-28 01:29 UTC, KevinMulhern commented on app/assets/stylesheets/components/form/form.scss
> +  .form__section.form__section--bottom > .button {
As discussed in discord we should have a wrapper div around the buttons instead.

2020-10-28 17:06 UTC, DoviMaj commented
@KevinMulhern the screenshots are at which width? when u say max-width what px is that? 

also there where some responsive issues with the create form that i tried resolving at once with the edits. 

![submit](https://user-images.githubusercontent.com/36450233/97470755-97cffb00-1950-11eb-83b8-32763179b4bd.gif)

2020-10-28 17:35 UTC, KevinMulhern commented
Those screen shots are over 1500px

2020-10-28 17:45 UTC, DoviMaj commented
ok ive improved the solution to solve both with media queries.

```
@media (max-width: 1510px){
    .form__section--bottom{
    display:block;
    text-align: center;
}
}

@media (max-width: 1153px){
    .form__section--bottom{
    display:flex;
    text-align: center;
}
}

@media (max-width: 652px){
    .form__section--bottom{
    display:block;
    text-align: center;
}
}

.form__section--right-aligned {
    align-items: center;
    justify-content:space-between
}

.form__toggle-checkbox {
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 20px
}

@media (max-width: 405px){
    .form__section.form__section--bottom > .button {   
    display: block;   
    margin: auto;
    }
}

```

the gifs start at 1800px:

![create-solution](https://user-images.githubusercontent.com/36450233/97475316-c7cdcd00-1955-11eb-91f2-f242cd59c3d2.gif)
![edit-solution](https://user-images.githubusercontent.com/36450233/97475481-f9df2f00-1955-11eb-9d6a-5d429d274142.gif)

2020-10-28 18:24 UTC, KevinMulhern commented
Yeah that looks like the correct behaviour @DoviMaj.

Are you testing these changes on a local version of the app? I noticed your using a patch branch.

2020-10-28 18:50 UTC, DoviMaj commented
i have a patch branch but im actually just testing inside a inspector stylesheet with dev tools.

should i proceed with those changes @KevinMulhern?

2020-10-28 20:01 UTC, leosoaivan commented
@KevinMulhern @DoviMaj could we just update the `react-modal__body` to have a default width of 60%, instead of 40%? The media queries are also included there, so we shouldn't need to include more media query rules. See here: https://github.com/TheOdinProject/theodinproject/blob/master/app/assets/stylesheets/components/react_modal.scss

2020-10-28 20:39 UTC, DoviMaj commented
@leosoaivan we can let it 60% by default but that doesn't make it responsive and the overflowing issue persist

2020-10-29 02:29 UTC, leosoaivan commented
I think it's possible.

![ezgif com-optimize](https://user-images.githubusercontent.com/13614862/97517916-8b599b80-196c-11eb-9ddd-243988d25a82.gif)

At the end of the day, I don't think we want to add custom media-query breakpoints, as we use the ones provided by Bootstrap, and changing the default width to 60% is a one-line change. If we add your wrapper div around the buttons as well, I think we have a good solution.

2020-10-29 15:28 UTC, DoviMaj commented
If that is the behavior we want il go for it. just pointing out that the content is right aligned on bigger screens and on smaller screens its left aligned and on mobile screens its all messed up. the same goes for the create form.

Also 60 % width looks weird on normal desktop imo, its huge.

Also i did what u said and didnt get the result u got at the screenshot. did u add or chenge some css @leosoaivan ?

2020-10-31 21:38 UTC, leosoaivan commented
@DoviMaj 

Yes, I changed the css in the file I linked above. Is that where you tried making the changes as well? We do want the changes for the content as well, of course, but I didn't focus on that in my example.

Like I mentioned above, if the modal is too big in wider screens, could we use the Bootstrap queries to add additional rules?

2020-11-01 16:31 UTC, DoviMaj commented
```
/*changed justify content to center and added flex wrap,
would make sense to rename class to center align*/
.form__section--right-aligned {
  justify-content: center;
  flex-wrap: wrap;
}

/*changed text align to center on existing media query*/
@media (max-width: 767.98px) {
.form__section--right-aligned {
  text-align: center;
  }
}

/*added margin and justify content center*/
.form__toggle-checkbox {
  margin-bottom: 10px;
  justify-content: center;
}

/*buttons wrapper div on edit form style*/
.form__section--bottom__buttons-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
  gap:10px
}
```
we can change the width to whatever we want with this solution because of the buttons wrapper div and `flex-wrap` magic. if it fits beside the toggle it stays there. if not, it goes down. its fully responsive yey!

What about this one @leosoaivan @KevinMulhern ?

![sl2](https://user-images.githubusercontent.com/36450233/97808553-4be2c600-1c70-11eb-9cb5-b526ea60b3d0.gif)
![sl3](https://user-images.githubusercontent.com/36450233/97808554-4dac8980-1c70-11eb-9d78-2ff29e9c751c.gif)

2020-11-01 19:06 UTC, leosoaivan commented
@DoviMaj
I like this solution a lot better. And you are right `.form__section--right-aligned` doesn't make sense anymore. What if we combined all the rules under `.form__section--bottom` and get rid of all instances of `.form__section--right-aligned` in the code? What do you think about that @KevinMulhern?

Also, for that media query, I think we can use the Bootstrap mixin `@include media-breakpoint-down(sm) { ... }`.

2020-11-01 20:22 UTC, DoviMaj commented
About the media query i didnt add it. i used the existing one that i belive is called: `@include media-breakpoint-down(md)` its just showing like that cause im using dev tools to play with it.

2020-11-10 16:58 UTC, DoviMaj commented
Whats up with this @KevinMulhern?

2020-11-10 20:50 UTC, KevinMulhern commented
Thanks for all your work on this @DoviMaj 💪

2020-11-10 20:51 UTC, merged

2020-11-10 20:54 UTC, DoviMaj commented
should i proceed with this changes? @KevinMulhern

2020-11-16 14:27 UTC, DoviMaj commented
@KevinMulhern did u open a new issue?

2020-11-16 22:14 UTC, KevinMulhern commented
I didn't, I'll reopen the old one.

2020-11-18 15:57 UTC, DoviMaj commented
ok. I'm just waiting for aproval of the latest solution and the changes to the class names @KevinMulhern whenever u can take a look.

2020-11-18 19:36 UTC, KevinMulhern commented
> ok. I'm just waiting for aproval of the latest solution and the changes to the class names @KevinMulhern whenever u can take a look.

Where is the latest solution at @DoviMaj?

2020-11-18 19:39 UTC, DoviMaj commented
> ```
> /*changed justify content to center and added flex wrap,
> would make sense to rename class to center align*/
> .form__section--right-aligned {
>   justify-content: center;
>   flex-wrap: wrap;
> }
> 
> /*changed text align to center on existing media query*/
> @media (max-width: 767.98px) {
> .form__section--right-aligned {
>   text-align: center;
>   }
> }
> 
> /*added margin and justify content center*/
> .form__toggle-checkbox {
>   margin-bottom: 10px;
>   justify-content: center;
> }
> 
> /*buttons wrapper div on edit form style*/
> .form__section--bottom__buttons-wrapper {
>   display: flex;
>   justify-content: center;
>   align-items: center;
>   flex-wrap: wrap;
>   gap:10px
> }
> ```
> 
> we can change the width to whatever we want with this solution because of the buttons wrapper div and `flex-wrap` magic. if it fits beside the toggle it stays there. if not, it goes down. its fully responsive yey!
> 
> What about this one @leosoaivan @KevinMulhern ?
> 
> ![sl2](https://user-images.githubusercontent.com/36450233/97808553-4be2c600-1c70-11eb-9cb5-b526ea60b3d0.gif)
> ![sl3](https://user-images.githubusercontent.com/36450233/97808554-4dac8980-1c70-11eb-9d78-2ff29e9c751c.gif)

2020-11-18 19:40 UTC, DoviMaj commented
after that Leo also had some coments: 

> @DoviMaj
> I like this solution a lot better. And you are right `.form__section--right-aligned` doesn't make sense anymore. What if we combined all the rules under `.form__section--bottom` and get rid of all instances of `.form__section--right-aligned` in the code? What do you think about that @KevinMulhern?
> 
> Also, for that media query, I think we can use the Bootstrap mixin `@include media-breakpoint-down(sm) { ... }`.