Add unit tests for like.js
TheOdinProject/theodinproject pull request #1535
Opened 2020-11-26 04:02 UTC by marvingay

https://github.com/TheOdinProject/theodinproject/issues/1506

This commit:
- Adds unit tests for the like.js component
- Adds aria label to icon in component for accessibility purposes.

2020-11-26 17:32 UTC, leosoaivan requested changes

2020-11-26 17:32 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/like.test.js
> +
Remove?

2020-11-26 17:32 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/like.test.js
> +})
Add newline.

2020-11-26 17:32 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/like.js
> +        {submission.likes} <i className={submission.is_liked_by_current_user ? 'fa fa-heart liked' : 'fa fa-heart'} aria-label='Like icon'></i>
👌

2020-11-27 17:40 UTC, leosoaivan approved these changes

2020-11-28 17:49 UTC, KevinMulhern commented
🚀

2020-11-28 17:49 UTC, merged