Added submission-title unit tests
TheOdinProject/theodinproject pull request #1538
Opened 2020-11-29 19:44 UTC by fortypercenttitanium

2020-11-30 21:35 UTC, KevinMulhern commented
Hi @fortypercenttitanium, thanks for submitting. Would you mind changing it to use 2 spaces for indentation please? we use that for indentation everywhere else and should keep it consistent :)

2020-11-30 22:16 UTC, fortypercenttitanium commented
Should be good now.

2020-12-01 03:55 UTC, leosoaivan requested changes

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +describe('Dashboard view true', () => {
The top level `describe` should describe what component is being tested. See the other tests for an example. You can nest the other `describes` under this top-level describe.

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +  it('shows the lesson title in dashboard view', () => {
I recommend using a consistent imperative verb across all your test cases that test whether or not something is displayed. "Shows" or "Displays" is good.

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +  it('has a link to the project in dashboard view', () => {
Use consistent imperative verb.

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +  it('returns username if not in dashboard mode', () => {
Use consistent imperative verb.

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +    render(<SubmissionTitle submission={submission} isDashboardView={true} />);
Write out in multi-line, since you are passing in more than 1 props. See other tests for example.

2020-12-01 03:55 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +    render(<SubmissionTitle submission={submission} isDashboardView={true} />);
Multi-line.

2020-12-01 12:43 UTC, fortypercenttitanium commented
Made requested changes :+1:

2020-12-01 15:06 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/submission-title.test.js
> +    isDashboardView={true} />);
Follow general indenting guidelines here:
```
render(
  <SubmissionTitle
    submission={submission}
    isDashboardView={true} 
  />
);
```
```

2020-12-02 03:44 UTC, leosoaivan approved these changes

2020-12-02 03:54 UTC, merged