Add unit tests for modal.js
TheOdinProject/theodinproject pull request #1549
Opened 2020-11-30 17:22 UTC by aayushmau5

#1507 

This commit:
- Adds unit tests for the modal.js component
- Adds aria labels in component for accessibility purposes.

2020-12-02 03:19 UTC, leosoaivan requested changes
Excellent start.

2020-12-02 03:19 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/modal.test.js
> +    expect(getByLabelText("modal--hidden")).toHaveClass("react-modal--hidden");
Test should not rely solely on an assertion on a class name, which is opaque and unnecessary to a user. Add an assertion that tests for the presence/absence of children, per line 14 of the component. You may want to pass in a simple `div` with some text to assert against.

2020-12-02 03:19 UTC, leosoaivan commented on app/javascript/components/project-submissions/components/__tests__/modal.test.js
> +    expect(getByLabelText("modal--shown")).toHaveClass("react-modal");
Same here: Add an assertion that tests for the presence/absence of children, per line 14 of the component.

2020-12-02 07:35 UTC, aayushmau5 commented
@leosoaivan Please check now.

2020-12-03 01:49 UTC, leosoaivan approved these changes

2020-12-03 01:49 UTC, merged