Feature: Select a Course instead of Switching to a Path
TheOdinProject/theodinproject pull request #1960
Opened 2021-05-19 23:39 UTC by KevinMulhern

#### Because:
Feedback from Ada:
> The wording of "switch" is confusing because once you’re prompted to pick a path, you essentially have not entered into either path yet so maybe the word "select" sounds more direct. "Switch" sounds like the user is already in something (which they are not)

#### This commit
* Replaces the "switch" copy with "select" which works for both cases of when a user has not chosen a path yet or decided to take the other path in the future.

#### Checklist
 - [ ] You have read [The Odin Projects Contributing Guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide)?
 - [ ] You have verified the tests and linters all pass against your changes?
 - [ ] You have included automated tests for your changes where applicable?

2021-05-19 23:58 UTC, rlmoser99 requested changes
Looks good to me, except for the small typo in a test.

2021-05-19 23:58 UTC, rlmoser99 commented on spec/system/select_path_spec.rb
> +RSpec.describe 'Seleting Paths', type: :system do
Small typo

2021-05-20 00:12 UTC, KevinMulhern commented
Great catch! thanks @rlmoser99 😄

2021-05-20 00:14 UTC, rlmoser99 approved these changes

2021-05-20 00:21 UTC, merged