Moved dotenv gem to dev/test group.
TheOdinProject/theodinproject pull request #2707
Opened 2022-03-08 23:17 UTC by linkonsat

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [ ] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-03-08 23:36 UTC, KevinMulhern requested changes

2022-03-08 23:36 UTC, KevinMulhern commented on Gemfile
> +  gem 'dotenv-rails', '~> 2.7'
Rubocop is complaining about the alphabetical order of the gems:
```
> Gemfile:60:3: C: [Correctable] Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem dotenv-rails should appear before rspec-rails.
  gem 'dotenv-rails', '~> 2.7'
```

I hate this rule, it always catches me out 😆

2022-03-09 15:15 UTC, CouchofTomato approved these changes

2022-03-09 22:17 UTC, KevinMulhern commented
Sorry to be a pain @linkonsat, just one more thing. Can we squash the `Moved dotenv to new line` commit into the first commit please?

2022-03-10 00:09 UTC, linkonsat commented
@KevinMulhern It's all good! I appreciate it since I learned the hard way how to squash. I realized I squashed a few commits outside of the ones I needed to squash. I didn't want to risk tampering with the commit history so I just opened a new PR [here}(https://github.com/TheOdinProject/theodinproject/pull/2711) to avoid any risks of commit history being changed. I will go ahead and close my PR if that's alright.

2022-03-10 21:54 UTC, closed without merging