Fix/update/javascript/faq/page/handling/issue#2376
TheOdinProject/theodinproject pull request #2710
Opened 2022-03-09 05:27 UTC by linkonsat

Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [ ] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**
This PR is the updated version of an already open one due to the local repo being deleted by accident. Incorporates the changes requested [here](https://github.com/TheOdinProject/theodinproject/pull/2485). As well as resolves an open issue.

Closes #2376 

**2. This PR:**

**3. Additional Information:**

2022-03-09 22:14 UTC, KevinMulhern requested changes

2022-03-09 22:14 UTC, KevinMulhern commented on app/javascript/controllers/reveal_controller.js
> +// reveal_controller.js
Sorry for the confusion @linkonsat, I know you got these comments from the example code, I should have made it clear the comments were annotations. The code should be clear enough without them though. Can we remove the comments in the js and HTML file please?

2022-03-09 22:14 UTC, KevinMulhern commented on app/views/static_pages/faq/_faq_card.html.erb
> +  </div></div> <!-- /.faq-card -->
Can we put this closing div on a new line please?

2022-03-09 22:14 UTC, KevinMulhern commented on app/views/static_pages/faq/_faq_card.html.erb
> +      <i class="fas fa-chevron-down"></i>
Just a little polish to make the chevrons fit better with the text sizing and color on the faq item:
```suggestion
      <i class="fas fa-chevron-down text-xl text-gray-500"></i>
```

2022-03-12 16:27 UTC, linkonsat commented
Changes were incorporated! I didn't see anything else that seemed off to me styling wise but if there is anything I can change let me know.

2022-03-12 19:03 UTC, KevinMulhern commented on app/javascript/controllers/reveal_controller.js
> +// reveal_controller.js
Can we remove the `// reveal_controller.js` comment as well please @linkonsat ?

2022-03-12 19:03 UTC, KevinMulhern commented on app/views/static_pages/faq/_faq_card.html.erb
> +  </div>
Looks like this just needs de-dented by one so it's flush with the opening tag.

2022-03-13 22:37 UTC, linkonsat commented
Changes incorporated. Do you want me to squash some of the commits together since it's quite a few? Thanks for your patience as well Kevin. Doing this PR definitely helped uncover some unclean code habits I had so appreciate the feedback a lot! Definitely going to incorporate the feedback in future PR's.

2022-03-13 23:16 UTC, KevinMulhern commented
Thanks for making those changes @linkonsat, this is looking great, nice work!

Yeah, lets squash the commits and get this merged mate 💪

2022-03-14 04:15 UTC, linkonsat commented
Squashed together the commits but for some reason, it pushed a whole bunch of other ones despite not having them in the rebase. Practiced squashing a branch in one of my repositories and didn't get the same behavior so opened up a new PR without all the other commits [here](https://github.com/TheOdinProject/theodinproject/pull/2719).

2022-03-14 23:35 UTC, closed without merging