Feature: updated color values for text color and background color in dark-mode
TheOdinProject/theodinproject pull request #3034
Opened 2022-06-30 18:54 UTC by joayo13

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [ ] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Closes #3033 

**2. This PR:**

- changed color values for bg-accent, bg-color, font-color, header-color to be easier on the eyes

**3. Additional Information:**

2022-06-30 19:18 UTC, KevinMulhern requested changes
Looks good to me @joayo13, thanks for doing this.

@thatblindgeye whats your thoughts on the contrast?

2022-06-30 19:18 UTC, KevinMulhern commented on app/assets/stylesheets/dark-mode.css
> +  }
Typo: extra space here

2022-07-01 16:58 UTC, thatblindgeye approved these changes
Looks good! Worth giving it a shot. The font color being less bright of a white should definitely help.

2022-07-01 20:37 UTC, KevinMulhern approved these changes

2022-07-01 20:37 UTC, merged