Chore: Convert "About" page to TailwindCSS
TheOdinProject/theodinproject pull request #3097
Opened 2022-07-17 18:54 UTC by leosoaivan

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Closes #XXXXX

**2. This PR:**

**3. Additional Information:**

2022-07-18 00:06 UTC, KevinMulhern requested changes

2022-07-18 00:06 UTC, KevinMulhern commented on app/views/static_pages/about/_overview.html.erb
> +<section class="py-12 sm:py-24 bg-gray-100">
[BUG] We'll need `odin-dark-bg` on this to override the gray on dark mode.

```suggestion
<section class="py-12 sm:py-24 bg-gray-100 odin-dark-bg">
```

<img width="1916" alt="Screenshot 2022-07-18 at 01 02 14" src="https://user-images.githubusercontent.com/7963776/179430180-96be6730-3331-4c8e-ba0b-15c8681ffab4.png">

2022-07-18 00:06 UTC, KevinMulhern commented on app/views/static_pages/about/_overview.html.erb
> +      <%= render CardComponent.new do |card| %>
[BUG] The stats cards aren't going full width at below the sm breakpoint:
<img width="480" alt="Screenshot 2022-07-18 at 00 59 14" src="https://user-images.githubusercontent.com/7963776/179430130-cecd00de-69b1-4e26-bd15-aa5667d3d7cb.png">

2022-07-18 00:07 UTC, KevinMulhern commented
Looking great @leosoaivan 💪 

Just some minor stuff I picked up on.

2022-08-07 18:46 UTC, leosoaivan commented on app/components/about_belief_component.html.erb
> +  <div class="sm:col-span-10 sm:pl-4 text-center sm:text-left">
_smaaaart_ 👍 😆

2022-08-07 18:56 UTC, leosoaivan commented on app/components/about_belief_component.html.erb
> +    <h3 class="pt-10 sm:pt-0 pb-4 text-xl">
TIL 👏

2022-08-07 18:58 UTC, leosoaivan commented on app/views/static_pages/about.html.erb
>            <h2 class="bold text-center beliefs-heading text-2xl">Our Beliefs</h2>
Had it at mb-16, but I think mb-10 looks better. Changing.

2022-08-07 19:03 UTC, leosoaivan commented on app/views/static_pages/about/_overview.html.erb
> +        <% card.body(classes: 'py-4 text-center' ) do %>
On one hand, totally agree. On the other, it creates an issue with the "Open source" text and image:

![image](https://user-images.githubusercontent.com/13614862/183306967-cbd576f0-00e7-4980-8610-343ccf86ba99.png)

How do you want to proceed?

2022-08-07 19:04 UTC, leosoaivan commented on app/views/static_pages/about/_overview.html.erb
> +        <% card.body(classes: 'py-4 text-center' ) do %>
![image](https://user-images.githubusercontent.com/13614862/183307004-ac26db61-ecfb-4d59-b6da-c1f1926adb9a.png)

2022-08-08 12:18 UTC, KevinMulhern commented on app/views/static_pages/about/_overview.html.erb
> +        <% card.body(classes: 'py-4 text-center' ) do %>
Smaller font looks great to me 👍

2022-08-08 12:18 UTC, KevinMulhern approved these changes
Nice work @leosoaivan this looks/feels solid 💪

2022-08-12 01:06 UTC, leosoaivan commented on app/views/static_pages/about.html.erb
>          <div class="col-lg-8 offset-lg-2">
Ah gotcha. Missed those.

2022-08-16 07:03 UTC, KevinMulhern approved these changes
Thanks for all your work on this @leosoaivan  🚀

2022-08-24 01:39 UTC, merged