Fix: Improve theme switcher UX (#3497)
TheOdinProject/theodinproject pull request #3844
Opened 2023-06-12 02:22 UTC by ChargrilledChook

**Because:**
* Current behaviour is inconsistent and confusing

**This PR:**
* Moves theme switcher out of dropdown menu when logged in
* Adjusts position to be consistent when logged in or out
* Tidy broken Lookbook previews due to removal of GA tracking

2023-06-14 01:04 UTC, KevinMulhern requested changes
Just a couple of styling tweaks to make it consistent with the other nav items:

The [base styling here](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/theme/switcher_component.yml#L7) needs its group hover updated to

```css
dark:group-hover:text-gray-300
```

And the [icon only styling](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/theme/switcher_component.yml#L10) here needs updated to:

```css
 icon_only: 'text-gray-400'
```

2023-06-18 03:01 UTC, ChargrilledChook commented
@KevinMulhern Done :heavy_check_mark:

2023-06-19 10:48 UTC, KevinMulhern commented on app/components/theme/switcher_component.yml
> +  icon_only: 'text-gray-500 group-hover:text-gray-400'
Sorry @ChargrilledChook, I didn't communicate this very well in the previous feedback. The light color just needs updated here, the dark hover should be ok.

```suggestion
  icon_only: 'text-gray-400 group-hover:text-gray-700'
```

2023-07-05 10:00 UTC, ChargrilledChook commented
Need to fix a spec; something has regressed after some other recent merges

2023-07-10 23:01 UTC, ChargrilledChook commented
Should be fine once #3948 is merged

2023-07-11 02:07 UTC, KevinMulhern approved these changes
🚀

2023-07-11 03:00 UTC, merged