How to ask a technical question: Fix a broken link
TheOdinProject/theodinproject pull request #4046
Opened 2023-07-31 01:47 UTC by Eveieve

## Because

- The `improve this lesson on github` link was broken 

## This PR

- Fix the broken link

## Issue

#4033
## Additional Information

I didn't realize this issue was something in regard to the `theodinproject` repository and not the `curriculum` repository of TOP. This is my first time contributing to this one, and I'm not quite sure if I solved the issue correctly. Below is the corrected link. 

- The current broken link is https://github.com/TheOdinProject/theodinproject/edit/main/app/views/static_pages/how_to_ask.html.erb
- The correct link should be https://github.com/TheOdinProject/theodinproject/edit/main/app/views/guides/community/how_to_ask.html.erb

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

2023-08-03 16:28 UTC, KevinMulhern requested changes

2023-08-03 16:28 UTC, KevinMulhern commented on app/views/guides/community/how_to_ask.html.erb
> +  <%= render 'guides/community/dashboard_steps/github_link', filename: 'app/views/guides/community/how_to_ask.html.erb' %>
The first argument is the name of the view partial we use for github linke. We just need to update the filename value we're passing to it as an argument:

```suggestion
  <%= render 'static_pages/dashboard_steps/github_link', filename: 'app/views/guides/community/how_to_ask.html.erb' %>
```

This should get all the tests passing again.

2023-08-04 11:30 UTC, ManonLef commented
FYI: Once you've made the requested changes, you can re-request a review from the reviewer that asked to make said changes :)

![Screenshot 2023-08-04 at 13 29 26](https://github.com/TheOdinProject/theodinproject/assets/81025586/2b53a289-4c9f-4f93-9f1f-d9bc79c2354e)

2023-08-04 20:22 UTC, KevinMulhern approved these changes
LGTM, thanks @Eveieve 💪

2023-08-04 20:22 UTC, merged