Give donate buttons slightly more horizontal space
TheOdinProject/theodinproject pull request #4079
Opened 2023-08-08 17:50 UTC by Asartea

## Because
Currently there is very little whitespace between the learn more and donate buttons, leading to a cramped feeling

## This PR
- Gives them both a bit of horizontal margin

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.

2023-08-09 08:42 UTC, KevinMulhern requested changes

2023-08-09 08:42 UTC, KevinMulhern commented on app/views/shared/_footer.html.erb
>        <div class="text-center mt-4">
Thanks for doing this @Asartea, definitely agree on giving these more space.

It looks like the margin on the outer edges is causing a bit of a responsive bug by pushing the buttons to a new line:
<img width="379" alt="Screenshot 2023-08-09 at 09 32 47" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/38cb231d-7713-47bf-841c-9953d6d31aaf">


But to simplify - Tailwind has a handy `space-` utility we can put on the the parent and take care of the gap and save us from giving each child element a margin.
 
```suggestion
      <div class="mt-4 flex justify-center space-x-6">
```

2023-08-09 08:43 UTC, ManonLef commented
Great call!
I do agree they look cramped. At first I saw the result by itself and thought it was a bit more than "slightly more" spacing. 
![Screenshot 2023-08-09 at 10 30 02](https://github.com/TheOdinProject/theodinproject/assets/81025586/e7fb8fc2-f658-49d1-ae57-49a3cf6d6ccb)

But looking at the majority of the pages where this shows up, it looks similar to the spacing of the lesson buttons. 
![Screenshot 2023-08-09 at 10 27 23](https://github.com/TheOdinProject/theodinproject/assets/81025586/976017c3-d606-48eb-92a8-0717e6c09c84)

I feel they could be moved slightly closer together still since the buttons are smaller than the lesson buttons, which would make them relatively similar. But that's up for personal preference I guess.

I'm also curious if there'd be a preference to adding the margin to the buttons or use a gap to the parent instead:
![Screenshot 2023-08-09 at 10 38 15](https://github.com/TheOdinProject/theodinproject/assets/81025586/b8730ab0-ff59-44ad-bb0d-dbfafc3de587)

I'd love to hear @KevinMulhern 's thoughts on this.

2023-08-09 08:49 UTC, Asartea commented
> I'm also curious if there'd be a preference to adding the margin to the buttons as you did, or use a gap to the parent instead:

As KevinMulhern correctly pointed out, Tailwind indeed has a great utility for this I forgot exists; see the updated PR.

> I feel they could be moved slightly closer together still since the buttons are smaller than the lesson buttons, which would make them relatively similar. But that's up for personal preference I guess.

I personally feel that as soon as they diverge too far from the spacing of the lesson buttons I start noticing the difference? But would love to hear a third opinion on this

> But looking at the majority of the pages where this shows up, it looks similar to the spacing of the lesson buttons.

You'd almost think that's what I based the spacing on :)

2023-08-09 13:30 UTC, KevinMulhern reviewed
I think,

2023-08-09 13:57 UTC, Asartea commented on app/views/shared/_footer.html.erb
> +        <%= link_to 'Learn more', support_us_path, class: 'button button--secondary mx-3' %>
*blinks* I was clearly not entirely awake when making these changes

2023-08-09 20:31 UTC, ManonLef commented
Looks great to me! ❤️

2023-08-10 08:14 UTC, KevinMulhern approved these changes
LGTM 🚀

2023-08-10 08:14 UTC, merged