Add feature to display the number of projects in each section
TheOdinProject/theodinproject pull request #4345
Opened 2024-01-17 15:25 UTC by sparshalc

Implementing a new feature to enhance the user experience by displaying the count of projects in each section. This feature addresses issue #4331.

![image](https://github.com/TheOdinProject/theodinproject/assets/116902652/6ded43e4-bcb1-481f-8093-24114b5d4a68)

2024-01-18 21:02 UTC, KevinMulhern requested changes

2024-01-19 09:58 UTC, sparshalc commented on db/seeds.rb
> +Course.find_each do |course|
Is /theodinproject/db/fixtures/paths/full_stack_rails/courses/databases.rb where you intend to put it?

2024-01-19 10:42 UTC, sparshalc commented on db/seeds.rb
> +Course.find_each do |course|
Is the intended location for it to be theodinproject/lib/seeds/course_builder.rb?

2024-01-23 01:12 UTC, KevinMulhern commented on db/seeds.rb
> +Course.find_each do |course|
We could put it there, but we'll also have to call it in all course files as an after action like we do with the [`destroy_removed_seeds`](https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/paths/full_stack_javascript/seed.rb#L24) method.

I think for now, following the same format as our success stories seeds should be good enough. We'll just update all course counts in one go -  we'll need to put it in this location: `db/seeds/update_course_counts.rb`

2024-01-23 21:56 UTC, KevinMulhern requested changes

2024-01-23 21:56 UTC, KevinMulhern commented on app/views/courses/_course.html.erb
> +              <span class="text-sm text-gray-500"><%= pluralize(course.lessons_count, 'Lesson') %></span>
Nit: Icon and text have different colors on dark mode, but we can inherit the color for both from the parent:

```suggestion
              <span class="text-sm "><%= pluralize(course.lessons_count, 'Lesson') %></span>
```

2024-01-23 21:56 UTC, KevinMulhern commented on app/views/courses/_course.html.erb
> +              <span class="text-sm text-gray-500"><%= pluralize(course.projects_count, 'Project') %></span>
Same here:

```suggestion
              <span class="text-sm"><%= pluralize(course.projects_count, 'Project') %></span>
```

2024-01-23 21:56 UTC, KevinMulhern commented on db/seeds.rb
> +# GENERATE COURSE Content
```suggestion
# GENERATE course lesson and project counts
```

2024-01-23 21:56 UTC, KevinMulhern commented on app/views/courses/_course.html.erb
> +          <div class="flex space-x-3 mt-2 sm:mt-1.5 sm:justify-center text-gray-500 dark:text-gray-400">
Nit: From testing, it looks like we don't need the sm: breakpoint on justify-center

```suggestion
          <div class="flex space-x-3 mt-2 sm:mt-1.5 justify-center text-gray-500 dark:text-gray-400">
```

2024-01-24 14:18 UTC, KevinMulhern requested changes
Thanks for making those changes, just one more small change and I think we're good to ship. We'll need the merge conflict fixed too.

2024-01-24 14:18 UTC, KevinMulhern commented on app/views/courses/_course.html.erb
> +              <%= inline_svg 'icons/book.svg', alt: 'lesson icon', class: 'w-6 h-6' %>
Final pass through - the icons are just a little too big and draw the eye too much. 5 seems to make them more proportionate to their surroundings. 

```suggestion
              <%= inline_svg 'icons/book.svg', alt: 'lesson icon', class: 'w-5 h-5' %>
```

Size difference can be seen with this, first course has the smaller icons and the second doesnt.
<img width="946" alt="Screenshot 2024-01-24 at 14 13 09" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/ae2ec106-b0d5-45f6-becb-95305ff8fffe">

2024-01-25 22:48 UTC, KevinMulhern approved these changes
Looking great, thanks @sparshalc

2024-01-25 22:48 UTC, merged