Rename JavaScript Foundation Lessons to be more descriptive
TheOdinProject/theodinproject pull request #4381
Opened 2024-02-11 22:34 UTC by nikitarevenco

## Because

The foundations lesson titled 'Fundamentals Part X' are not descriptive of what they actually teach, and should be renamed.

## This PR

Rename fundamentals parts 1-5 to:

- Variables and operators
- Data types and conditionals
- Function basics
- Arrays and loops
- Object basics 

## Issue

Closes #[27278](https://github.com/TheOdinProject/curriculum/issues/27278)

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] I have verified all tests and linters pass after making these changes.
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

2024-02-11 23:09 UTC, JoshDevHub requested changes
This is a cool improvement! Nice to have actual names for these lessons.

You'll have to make a few more changes for this to function properly:
1. In `db/fixtures/lessons/foundation_lessons.rb`, you've changed the key, the title name, and the description. You also need to change the `github_path`. This is used to pull the lesson content from the curriculum github repo. In your PR to the curriculum repo, you've changed the name of these files, so a github path like `/foundations/javascript_basics/fundamentals-3.md` isn't going to exist.
2. You need to update [this section](https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/paths/foundations/seed.rb#L137-L154) of the `db/fixtures/paths/foundations/seed.rb` file. These fetch calls will use the key names defined in the lessons fixture, so a fetch on `'Fundamentals Part 1'` is going to fail. You need to update the relevant lessons to use the new key names.

Let me know if you have any questions about any of this. I suspect Ruby and Rails are unfamiliar territory for you.

2024-02-11 23:31 UTC, nikitarevenco commented
> This is a cool improvement! Nice to have actual names for these lessons.
> 
> You'll have to make a few more changes for this to function properly:
> 
> 1. In `db/fixtures/lessons/foundation_lessons.rb`, you've changed the key, the title name, and the description. You also need to change the `github_path`. This is used to pull the lesson content from the curriculum github repo. In your PR to the curriculum repo, you've changed the name of these files, so a github path like `/foundations/javascript_basics/fundamentals-3.md` isn't going to exist.
> 2. You need to update [this section](https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/paths/foundations/seed.rb#L137-L154) of the `db/fixtures/paths/foundations/seed.rb` file. These fetch calls will use the key names defined in the lessons fixture, so a fetch on `'Fundamentals Part 1'` is going to fail. You need to update the relevant lessons to use the new key names.
> 
> Let me know if you have any questions about any of this. I suspect Ruby and Rails are unfamiliar territory for you.

Got it. I've made the changes to the paths and also the fetch to call the correct name. 

And yeah, despite the syntax being different than javascript I can mostly read the code which is awesome.

2024-02-12 17:56 UTC, JoshDevHub requested changes
Just one tiny fix, then we should be good to merge.

2024-02-12 17:56 UTC, JoshDevHub commented on db/fixtures/lessons/foundation_lessons.rb
> +      description: "In this lesson we learn about variables and operators.",
```suggestion
      description: 'In this lesson we learn about variables and operators.',
```
Need this string in single quotes to make the linter happy.

2024-02-12 18:56 UTC, nikitarevenco commented
> Just one tiny fix, then we should be good to merge.

Done

2024-02-12 23:01 UTC, JoshDevHub approved these changes
Thank you for contributing!

2024-02-12 23:02 UTC, merged