Feature: courses use the split lesson/project counts
TheOdinProject/theodinproject pull request #4575
Opened 2024-06-19 23:00 UTC by BodiAli

## Because

The purpose of this PR is that it reduces confusion on how much lessons each course have in the dashboard interface by displaying the number of lessons independently from the number of projects, as I already clarified in this issue I opened: #4542

## This PR

* Courses viewed in the dashboard now follows the syntax of: "(Number of lessons) Lesson(s) / (Number of projects) Project(s)"

## Issue

Closes #4542

## Additional Information

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, this PR includes new or updated automated tests

2024-06-20 00:11 UTC, KevinMulhern requested changes
Thanks for doing this @BodiAli!

We should be consistent with how we display these counts. Can we use the same design with icons as we have on the course card with this please? 

<img width="917" alt="Screenshot 2024-06-20 at 01 03 03" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/74f1879b-93d7-41bf-b588-1249344888e7">

We can extract the [count markup](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/courses/_course.html.erb#L17) to [a partial](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials) to easily use it in both screens, and make sure future any updates will be be applied everywhere its used.

2024-06-20 01:02 UTC, BodiAli commented
Can you clarify more on what you mean? @KevinMulhern 

Is it the icons for lessons and projects that must be added?

2024-06-20 01:55 UTC, KevinMulhern commented
No problem @BodiAli, yep, pretty much just the icons. We want the counts to look exactly the same on both the course and dashboard screens.

2024-06-22 14:35 UTC, BodiAli commented
Anything else I can do? @KevinMulhern

2024-06-24 01:29 UTC, KevinMulhern commented
Sorry for the delay @BodiAli, this looks great!

I noticed when there is more than one course, the counts stand out and draw the eye a little too much. I'm not exactly sure what needs to be done, so won't hold up this PR with it and explore that myself.

Thanks again for doing this!

2024-06-24 01:29 UTC, KevinMulhern approved these changes

2024-06-24 01:29 UTC, merged

2024-06-24 02:00 UTC, BodiAli commented
It is an honor to work for this community and website! If you need anything else feel free to ask me :) @KevinMulhern