feat: node revamp milestone 1
TheOdinProject/theodinproject pull request #4582
Opened 2024-06-25 12:08 UTC by 01zulfi

## Because

node revamp

## This PR

node revamps

## Issue

Closes #XXXXX

## Additional Information

## Pull Request Requirements

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [ ] The `Because` section summarizes the reason for this PR
-   [ ] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] I have verified all tests and linters pass after making these changes.
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

2024-07-15 20:02 UTC, MaoShizhong commented
Just a heads up that the new env lesson will need adding here too :tada:

2024-07-18 12:53 UTC, MaoShizhong commented on db/fixtures/paths/full_stack_javascript/courses/databases.rb
> +  section.description = 'ORMS in Node.js does a lot of the heavy lifting with connecting and querying a database but there will be times you need to tweak a query to the database using raw SQL. Learn
Nit
```suggestion
  section.description = 'ORMs in Node.js do a lot of the heavy lifting with connecting and querying a database but there will be times you need to tweak a query to the database using raw SQL. Learning how to query efficiently will help your understanding of what Rails helps abstract away.'
```

2024-07-18 12:53 UTC, MaoShizhong commented on db/fixtures/paths/full_stack_javascript/courses/node_js.rb
> +  section.description = 'Here we finally get to Express, the most popular back-end JavaScript framework, and learn to build applications with PostgreSQL database.'
Nit
```suggestion
  section.description = 'Here we finally get to Express, the most popular back-end JavaScript framework, and learn to build applications with a PostgreSQL database.'
```

2024-07-18 12:53 UTC, MaoShizhong commented on db/fixtures/lessons/node_js_lessons.rb
>      },
The lessons are applied in `node_js.rb` as
`Forms and Data Handling` -> `Installing PostgreSQL` -> `Using PostgreSQL`

Even if functionally it makes no difference, probably best to have the lessons in the same order in this file for consistency.

2024-07-18 14:48 UTC, MaoShizhong requested changes

2024-07-18 14:48 UTC, MaoShizhong commented on db/fixtures/paths/full_stack_javascript/courses/node_js.rb
The course description on line 6 will need amending to reference PostgreSQL

2024-07-18 15:24 UTC, 01zulfi commented on db/fixtures/paths/full_stack_javascript/courses/node_js.rb
nice catch

2024-07-18 16:15 UTC, KevinMulhern approved these changes
Looks great to me @01zulfi! excited to see this go out 🔥

2024-07-18 16:44 UTC, MaoShizhong approved these changes
:rocket:

2024-07-18 18:54 UTC, merged